tabela_brasileiro = ('São Paulo', 'Coritiba', 'Corinthians', 'Atlético-MG', 'Ceará', 'Avaí', 'Cuiabá', 'Juventude', 'Bragantino', 'Atlético-GO', 'Flamengo', 'Fluminense', 'Santos', 'Palmeiras', 'América-MG', 'Fortaleza', 'Botafogo', 'Internacional', 'Goiás', 'Athletico-PR')
print('=*'* 50)
print('\nOs 5 primeiros colocados: ')
print(tabela_brasileiro[0:5])
print('\n Os 4 últimos colocados: ')
print(tabela_brasileiro[-4:])
print('\nOs times em ordem alfabética são:')
print(sorted(tabela_brasileiro))
print(f'\nO Bragantino está na {tabela_brasileiro.index("Bragantino") + 1}º posição')
